language: python
filter_secrets: false   # https://github.com/travis-ci/travis-ci/issues/8934


before_install:
  - deactivate
  # Do not buffer python outputs; flush them directly to the terminal
  - export PYTHONUNBUFFERED=true
  # Sets up a miniconda environment
  - source devtools/ci/miniconda_install.sh

install:
  # this is the conda-build based installation
  #- conda install --yes conda-build
  #- conda build devtools/conda-recipe
  #- conda create --quiet --yes --name test --use-local openpathsampling-dev
  #- source activate test
  # install by without conda-build (requirements, then setup.py install)
  - conda create -q -y --name test conda pyyaml python=$CONDA_PY
  - source activate test
  - conda config --env --add pinned_packages python=$CONDA_PY
  - export PACKAGES=`python devtools/install_recipe_requirements.py --dry devtools/conda-recipe/meta.yaml`
  - TESTING_PACKAGES=`cat devtools/testing_requirements.txt | tr "\n" " "`
  - EXTRA_PACKAGES=`cat devtools/optional_packages.txt | tr "\n" " "`
  - export PACKAGES="$PACKAGES $TESTING_PACKAGES $EXTRA_PACKAGES"
  - echo $PACKAGES
  - conda install -y -q -c conda-forge -c omnia $PACKAGES
  
  # report info about our conda env and finish installation
  - conda info --envs
  #- conda install --quiet --yes -c conda-forge msmbuilder
  #- conda install --quiet --yes nose python-coveralls ipynbtest 
  #- conda install --quiet --yes pytest 
  - conda config --env --add pinned_packages libnetcdf=4.6.1
  - conda config --env --add pinned_packages pytest-cov=2.5.1
  - conda config --env --add pinned_packages ipython!=7.4.0
  - conda update --all --yes --use-local --quiet
  # pin pytest-cov b/c: https://github.com/z4r/python-coveralls/issues/66
  # usually this should be before the conda update
  #- conda install --quiet --yes pytest-cov=2.5.1
  - conda update --quiet --yes matplotlib  # no idea why pytest-cov downgraded
  - python setup.py install

before_script:
  - python --version
  - python -c "import openpathsampling"
  - source devtools/ci/git_hash.sh
  - conda list -n test

script:
  - source devtools/ci/pytests.sh
  - source devtools/ci/ipythontests.sh

  # Upload new docs
  - bash -x devtools/ci/after_sucess.sh

addons:
  apt:
    packages:
    - pandoc

env:
  global:
    - secure: "NJvoSrLNd2ZR3HluJjEqI36gD5lsucwIvgnYjNmM4cwnnA77aLV9FRYTwlLRZn3XY9FL8KOzL5l0amNzMD7sQrf7bWwWv7iCUBddH549q9RSgiuOugtodYJ6VaXi76hk1rOgcJpDoCj9wTCIlMtWibPUzr1QHmdihfdM2iA2kkE="
    - secure: "l9NJkZDD0ALhkErUvhRrreLsrcWErd+CXpWv8dxHGtkjemNx6CwVtyL+a30jz/QwMANSZbKll/cPK5yJQvuwDaWxja6UPLLKVNGtma+CmwKcIC/wwTwbMoxcS62fyLJ3kS0qR8oCQz2nCPKiYyRGADtPLWVMZckY1SJfNYcKuCM="
    - secure: "kb37xmsSV3pEnESnINzwlW2Cju/UFzA/G+m+NsihAwO8RMPZwKCrZK/rptgkUDACXJxom5M690WEukQkHnOt+OTrWhu7WKZgYeVuWUs2++RohYv/m5npaOHMMn+uYmF328v4PvPmXxbD02zzg5Tgdn82x8oa6J8BKX8ohOQ6Xpg="
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.5
    - CONDA_PY=3.6
