package:
  name: openpathsampling-dev
  version: "0.9.6"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - future
    - setuptools
    #- numpy

  run:
    - python
    - numpy
    - scipy
    - future
    - pandas
    - netcdf4
    - libnetcdf==4.6.1
    - openmm
    - openmmtools
    - jupyter
    - ipython!=7.4.0
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson
    #- msmbuilder
    - pyemma

test:
  imports:
    - openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
